/* Lab reference ranges + medicine knowledge + diagnosis map.
   Sources: commonly used Indian lab normals; LOINC / ICD-10 / SNOMED CT codes for ABDM/FHIR alignment.
   Educational only — not medical advice. */

const LAB_REFERENCE = [
  { key: "hba1c", names: ["hba1c", "glycated hemoglobin", "glycosylated hemoglobin"], unit: "%", low: 4.0, high: 5.6, borderlineHigh: 6.4, loinc: "4548-4", display: "HbA1c",
    meaning: { en: "Average blood sugar over ~3 months. 5.7–6.4% is prediabetes range, 6.5%+ is diabetes range. Higher means sugar stayed high for weeks.",
      hi: "लगभग 3 महीने की औसत शुगर। 5.7–6.4% प्री-डायबिटीज, 6.5%+ डायबिटीज रेंज। ज्यादा मतलब हफ्तों से शुगर बढ़ी रही।",
      te: "సుమారు 3 నెలల సగటు షుగర్. 5.7–6.4% ప్రీ-డయాబెటిస్, 6.5%+ డయాబెటిస్ పరిధి.",
      ta: "சுமார் 3 மாத சராசரி சர்க்கரை. 5.7–6.4% முன்-நீரிழிவு, 6.5%+ நீரிழிவு வரம்பு." } },
  { key: "fbs", names: ["fasting blood sugar", "fasting glucose", "fbs", "fasting blood glucose"], unit: "mg/dL", low: 70, high: 100, borderlineHigh: 125, loinc: "1558-6", display: "Fasting Glucose",
    meaning: { en: "Sugar after overnight fast. 100–125 is impaired (prediabetes), 126+ on repeat tests is diabetes range.",
      hi: "रात भर उपवास के बाद शुगर। 100–125 बॉर्डरलाइन, बार-बार 126+ डायबिटीज रेंज।",
      te: "ఉపవాసం తర్వాత షుగర్. 100–125 సరిహద్దు, పదేపదే 126+ డయాబెటిస్ పరిధి.", ta: "உண்ணாவிரதத்திற்கு பிறகு சர்க்கரை. 100–125 எல்லை, தொடர்ந்து 126+ நீரிழிவு." } },
  { key: "ppbs", names: ["ppbs", "post prandial", "postprandial glucose", "pp blood sugar"], unit: "mg/dL", low: 70, high: 140, borderlineHigh: 199, loinc: "2571-8", display: "Post-meal Glucose",
    meaning: { en: "Sugar ~2 hours after food. Above 200 often suggests diabetes; 140–199 is impaired tolerance.",
      hi: "खाने के ~2 घंटे बाद शुगर। 200+ अक्सर डायबिटीज की ओर इशारा, 140–199 बॉर्डरलाइन।",
      te: "భోజనం తర్వాత ~2 గంటలకు షుగర్. 200+ డయాబెటిస్ సూచన.", ta: "உணவுக்கு ~2 மணி பிறகு சர்க்கரை. 200+ நீரிழிவு குறிப்பு." } },
  { key: "hemoglobin", names: ["hemoglobin", "haemoglobin", "hb"], unit: "g/dL", low: 12.0, high: 16.0, loinc: "718-7", display: "Hemoglobin",
    meaning: { en: "Protein in red blood that carries oxygen. Low means anemia — tiredness, weakness, breathlessness.",
      hi: "खून में ऑक्सीजन ले जाने वाला प्रोटीन। कम मतलब एनीमिया — थकान, कमजोरी।",
      te: "ఆక్సిజన్ మోసే ప్రోటీన్. తక్కువ అంటే రక్తహీనత — అలసట, బలహీనత.", ta: "ஆக்ஸிஜனை சுமக்கும் புரதம். குறைவு எனில் இரத்தசோகை — சோர்வு." } },
  { key: "wbc", names: ["wbc", "white blood cell", "total leukocyte", "tlc", "leukocyte"], unit: "/µL", low: 4000, high: 11000, loinc: "6690-2", display: "WBC (infection fighters)",
    meaning: { en: "Infection-fighting cells. High often means infection/inflammation; very low needs prompt medical review.",
      hi: "संक्रमण से लड़ने वाली कोशिकाएं। ज्यादा अक्सर संक्रमण/सूजन, बहुत कम तुरंत डॉक्टर को दिखाएं।",
      te: "ఇన్ఫెక్షన్‌తో పోరాడే కణాలు. ఎక్కువ అంటే ఇన్ఫెక్షన్.", ta: "தொற்றை எதிர்க்கும் செல்கள். அதிகம் எனில் தொற்று." } },
  { key: "platelet", names: ["platelet", "platelets", "thrombocyte"], unit: "/µL", low: 150000, high: 450000, loinc: "777-3", display: "Platelets (clotting)",
    meaning: { en: "Cells that help blood clot. Low can cause bleeding/bruising (seen in dengue); high can mean inflammation.",
      hi: "खून का थक्का बनाने वाली कोशिकाएं। कम होने पर खून/नील पड़ सकता है (डेंगू में)।",
      te: "రక్తం గడ్డకట్టడానికి సహాయపడే కణాలు. తక్కువ అంటే రక్తస్రావం ప్రమాదం.", ta: "இரத்தம் உறைய உதவும் செல்கள். குறைவு எனில் இரத்தக்கசிவு ஆபத்து." } },
  { key: "creatinine", names: ["creatinine", "serum creatinine"], unit: "mg/dL", low: 0.6, high: 1.2, loinc: "2160-0", display: "Creatinine (kidney)",
    meaning: { en: "Waste filtered by kidneys. High may mean kidneys are not filtering well — needs doctor review, hydration/meds check.",
      hi: "किडनी से छनने वाला अपशिष्ट। ज्यादा मतलब किडनी ठीक से छान नहीं रही — डॉक्टर से पूछें।",
      te: "మూత్రపిండాలు వడపోసే వ్యర్థం. ఎక్కువ అంటే మూత్రపిండాల సమస్య కావచ్చు.", ta: "சிறுநீரகம் வடிகட்டும் கழிவு. அதிகம் எனில் சிறுநீரக பிரச்சினை இருக்கலாம்." } },
  { key: "cholesterol", names: ["total cholesterol", "cholesterol"], unit: "mg/dL", low: 0, high: 200, borderlineHigh: 239, loinc: "2093-3", display: "Total Cholesterol",
    meaning: { en: "Fat in blood. Above 200 is borderline-high, 240+ is high — raises heart-disease risk over time.",
      hi: "खून में वसा। 200+ बॉर्डरलाइन, 240+ ज्यादा — लंबे समय में दिल का जोखिम।",
      te: "రక్తంలో కొవ్వు. 200+ సరిహద్దు, 240+ ఎక్కువ — గుండె ప్రమాదం.", ta: "இரத்தத்தில் கொழுப்பு. 200+ எல்லை, 240+ அதிகம்." } },
  { key: "ldl", names: ["ldl", "ldl cholesterol", "low density lipoprotein"], unit: "mg/dL", low: 0, high: 100, borderlineHigh: 159, loinc: "2089-1", display: "LDL (bad cholesterol)",
    meaning: { en: "'Bad' cholesterol that clogs arteries. Under 100 is ideal; higher raises heart-attack/stroke risk.",
      hi: "'खराब' कोलेस्ट्रॉल जो नसों में जमता है। 100 से नीचे आदर्श।",
      te: "'చెడు' కొలెస్ట్రాల్. 100 కంటే తక్కువ ఆదర్శం.", ta: "'கெட்ட' கொழுப்பு. 100க்கு கீழ் சிறந்தது." } },
  { key: "hdl", names: ["hdl", "hdl cholesterol", "high density lipoprotein"], unit: "mg/dL", low: 40, high: 100, loinc: "2085-9", display: "HDL (good cholesterol)",
    meaning: { en: "'Good' cholesterol that protects the heart. 40+ for men, 50+ for women is desirable; higher is better.",
      hi: "'अच्छा' कोलेस्ट्रॉल जो दिल की रक्षा करता है। ज्यादा बेहतर।",
      te: "'మంచి' కొలెస్ట్రాల్. ఎక్కువ మంచిది.", ta: "'நல்ல' கொழுப்பு. அதிகம் நல்லது." } },
  { key: "triglycerides", names: ["triglyceride", "triglycerides", "trig"], unit: "mg/dL", low: 0, high: 150, borderlineHigh: 199, loinc: "2571-8", display: "Triglycerides",
    meaning: { en: "Another blood fat. Above 150 is high — linked to diet, sugar, thyroid; raises heart/pancreas risk.",
      hi: "खून की एक और वसा। 150+ ज्यादा — खानपान/शुगर से जुड़ा।",
      te: "మరో రక్త కొవ్వు. 150+ ఎక్కువ.", ta: "மற்றொரு இரத்த கொழுப்பு. 150+ அதிகம்." } },
  { key: "tsh", names: ["tsh", "thyroid stimulating hormone"], unit: "µIU/mL", low: 0.4, high: 4.0, loinc: "3016-3", display: "TSH (thyroid)",
    meaning: { en: "Thyroid control hormone. High often means underactive thyroid (weight gain, tiredness); low means overactive.",
      hi: "थायरॉइड कंट्रोल हार्मोन। ज्यादा अक्सर थायरॉइड कम काम कर रहा, कम मतलब ज्यादा सक्रिय।",
      te: "థైరాయిడ్ హార్మోన్. ఎక్కువ అంటే తక్కువ పనితీరు.", ta: "தைராய்டு ஹார்மோன். அதிகம் எனில் குறை செயல்பாடு." } },
  { key: "bp_sys", names: ["systolic", "sys"], unit: "mmHg", low: 90, high: 120, borderlineHigh: 139, loinc: "8480-6", display: "BP Systolic (upper)",
    meaning: { en: "Upper BP number (pressure when heart beats). 120+ elevated, 140+ is high BP range.",
      hi: "BP की ऊपर वाली संख्या। 140+ हाई BP रेंज।", te: "BP పై సంఖ్య. 140+ అధిక BP.", ta: "BP மேல் எண். 140+ உயர் BP." } },
  { key: "vitd", names: ["vitamin d", "vit d", "25-oh vitamin d"], unit: "ng/mL", low: 30, high: 100, loinc: "1989-3", display: "Vitamin D",
    meaning: { en: "Bone/immunity vitamin. Below 20 is deficiency, 20–29 insufficiency — bone pain, tiredness, frequent illness.",
      hi: "हड्डी/इम्यूनिटी विटामिन। 20 से कम कमी — हड्डी दर्द, थकान।",
      te: "ఎముక విటమిన్. 20 కంటే తక్కువ లోపం.", ta: "எலும்பு வைட்டமின். 20க்கு கீழ் குறைபாடு." } },
];

const COMMON_MEDICINES = [
  "metformin","glimepiride","glibenclamide","gliclazide","insulin glargine","insulin aspart",
  "amlodipine","losartan","telmisartan","olmesartan","atenolol","metoprolol","enalapril","hydrochlorothiazide",
  "atorvastatin","rosuvastatin","simvastatin",
  "aspirin","ecosprin","clopidogrel",
  "paracetamol","dolo","crocin","ibuprofen","diclofenac",
  "azithromycin","amoxicillin","augmentin","cefixime","doxycycline","levocetirizine","cetirizine","montelukast",
  "omeprazole","pantoprazole","rabeprazole","domperidone",
  "thyroxine","eltroxin","thyronorm",
  "vitamin d","calcium","iron","folic acid","vitamin b12","zincovit","shelcal",
  "salbutamol","budesonide","foracort",
  "ondansetron","emetron","meftal","mefenamic"
];

const DIAGNOSIS_MAP = [
  { match: ["type 2 diabetes", "t2dm", "diabetes mellitus type 2", "diabetes"], code: "E11", system: "ICD-10", display: "Type 2 diabetes mellitus", snomed: "44054006" },
  { match: ["hypertension", "high blood pressure", "htn", "essential hypertension"], code: "I10", system: "ICD-10", display: "Essential hypertension", snomed: "59621000" },
  { match: ["dengue", "dengue fever"], code: "A90", system: "ICD-10", display: "Dengue fever", snomed: "38362002" },
  { match: ["anemia", "anaemia", "low hemoglobin", "iron deficiency"], code: "D64.9", system: "ICD-10", display: "Anemia", snomed: "271737000" },
  { match: ["hypothyroidism", "underactive thyroid"], code: "E03.9", system: "ICD-10", display: "Hypothyroidism", snomed: "40930008" },
  { match: ["hyperlipidemia", "high cholesterol", "dyslipidemia", "high triglycerides"], code: "E78.5", system: "ICD-10", display: "Hyperlipidemia", snomed: "55822004" },
  { match: ["asthma"], code: "J45", system: "ICD-10", display: "Asthma", snomed: "195967001" },
  { match: ["viral fever", "acute febrile illness", "fever"], code: "R50.9", system: "ICD-10", display: "Fever", snomed: "386661006" },
  { match: ["gastritis", "acidity", "gerd", "acid reflux"], code: "K29.7", system: "ICD-10", display: "Gastritis", snomed: "4556007" },
  { match: ["urti", "upper respiratory", "common cold", "cough and cold"], code: "J06.9", system: "ICD-10", display: "Upper respiratory infection", snomed: "54150009" },
];
